{
 "title": "AuxTel Overview",
 "time": { "from": "now/d", "to": "now/d" },
 "refresh": "5m",
 "panels": [
  {
   "title": "Summary State",
   "type": "table",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT \n  quote('atArchiver') as 'CSC',\n  date_time as 'Datetime',\n  summaryStateValue as 'Summary State',\n  priority as 'Priority'\nfrom atArchiver_logevent_summaryState order by date_time desc limit 1;"
    },
    {
     "rawSql": "SELECT \n  quote('atcamera') as 'CSC',\n  date_time as 'Datetime',\n  summaryStateValue as 'Summary State',\n  priority as 'Priority'\nfrom atcamera_logevent_summaryState order by date_time desc limit 1;"
    },
    {
     "rawSql": "SELECT \n  quote('atHeaderService') as 'CSC',\n  date_time as 'Datetime',\n  summaryState as 'Summary State',\n  priority as 'Priority'\nfrom atHeaderService_logevent_summaryState order by date_time desc limit 1;"
    }
   ]
  },
  {
   "title": "CCD Temperature",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 10, "y": 0 },
   "format": "celsius",
   "valueName": "first",
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(date_time) as time_sec,\n  ccdTemp0\nFROM atcamera_wreb\nWHERE $__timeFilter(date_time)\nORDER BY date_time DESC\n"
    }
   ]
  },
  {
   "title": "HV Bias",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 10, "y": 3 },
   "format": "volt",
   "valueName": "first",
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(date_time) as time_sec,\n  hvbias_V as 'HV Bias'\nFROM atcamera_wrebPower\nWHERE $__timeFilter(date_time)\nORDER BY date_time DESC"
    }
   ]
  },
  {
   "title": "Heater",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 10, "y": 6 },
   "format": "volt",
   "valueName": "first",
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(date_time) as time_sec,\n  heater_V as 'Heater'\nFROM atcamera_wrebPower\nWHERE $__timeFilter(date_time)\nORDER BY date_time DESC\n"
    }
   ]
  },
  {
   "title": "Latest Images",
   "type": "table",
   "gridPos": { "h": 9, "w": 15, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT date_time, imageName, imagesInSequence, exposureTime\nFROM atcamera_logevent_endOfImageTelemetry\nORDER BY date_time DESC"
    }
   ]
  }
 ]
}