{
 "title": "AuxTel WREB",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "auxtel_wreb_voltages1",
    "label": "AuxTel WREB Voltages Set 1",
    "query": "ckPSH_V,ckPOV,ogoV,cks0V,rg0V,od0V,rd0V,gd0V"
   },
   { "name": "auxtel_wreb_currents1", "label": "AuxTel WREB Currents Set 1", "query": "od0I" },
   {
    "name": "auxtel_wreb_voltages2",
    "label": "AuxTel WREB Voltages Set 2",
    "query": "digPS_V,anaPS_V,clkHPS_V,odPS_V,htrPS_V,power,sckU_V,sckL_V,rgU_V,rgL_V"
   },
   {
    "name": "auxtel_wreb_currents2",
    "label": "AuxTel WREB Currents Set 2",
    "query": "digPS_I,anaPS_I,clkHPS_I,odPS_I,htrPS_I"
   }
  ]
 },
 "panels": [
  {
   "title": "Voltages Set 1",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "volt" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(date_time) as time_sec,\n  ${auxtel_wreb_voltages1:csv}\nFROM atcamera_wreb\nWHERE $__timeFilter(date_time)\nORDER BY date_time ASC\n"
    }
   ]
  },
  {
   "title": "Voltages Set 2",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "volt" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(date_time) as time_sec,\n  ${auxtel_wreb_voltages2:csv}\nFROM atcamera_wreb\nWHERE $__timeFilter(date_time)\nORDER BY date_time ASC\n"
    }
   ]
  },
  {
   "title": "Currents Set 1",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "mamp" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(date_time) as time_sec,\n  ${auxtel_wreb_currents1:csv}\nFROM atcamera_wreb\nWHERE $__timeFilter(date_time)\nORDER BY date_time ASC\n"
    }
   ]
  },
  {
   "title": "Currents Set 2",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "mamp" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(date_time) as time_sec,\n  ${auxtel_wreb_currents2:csv}\nFROM atcamera_wreb\nWHERE $__timeFilter(date_time)\nORDER BY date_time ASC\n"
    }
   ]
  }
 ]
}