{
 "title": "Network Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Chile Time", "type": "grafana-clock-panel", "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 } },
  { "title": "Tucson Time", "type": "grafana-clock-panel", "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 } },
  { "title": "NCSA Time", "type": "grafana-clock-panel", "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 } },
  { "title": "SLAC Time", "type": "grafana-clock-panel", "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 } },
  {
   "title": "Output Throughput DWDM",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 0 },
   "format": "bps",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "1m" ], "type": "time" }
     ],
     "measurement": "snmp",
     "select": [
      [
       { "params": [ "ifHCOutOctets" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "*8" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "enclave", "operator": "=", "value": "net" },
      { "condition": "AND", "key": "node_name", "operator": "=", "value": "cisco" },
      { "condition": "AND", "key": "ifName", "operator": "=", "value": "Te1/1/3" }
     ]
    }
   ]
  },
  {
   "title": "Ping to core in the summit",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 0 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "measurement": "ping",
     "select": [
      [
       { "params": [ "average_response_ms" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=", "value": "core" }
     ]
    }
   ]
  },
  {
   "title": "Network Monitoring - Input",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "DLink Gi$tag_ifName",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "ifName" ], "type": "tag" }
     ],
     "measurement": "snmp",
     "query": "SELECT derivative(\"ifHCInOctets\", 1s) *8 AS \"Inbound\", derivative(\"ifHCOutOctets\", 1s) *-8 AS \"Outbound\" FROM \"snmp\" WHERE (\"device\" = 'switch' AND \"ifName\" = '1/48') AND $timeFilter GROUP BY \"ifName\"",
     "select": [
      [
       { "params": [ "ifHCInOctets" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "*8" ], "type": "math" },
       { "params": [ "Inbound" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=", "value": "switch" },
      { "condition": "AND", "key": "ifName", "operator": "=", "value": "1/48" }
     ]
    },
    {
     "alias": "3850 Gi$tag_ifName",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "ifName" ], "type": "tag" }
     ],
     "measurement": "snmp",
     "query": "SELECT derivative(\"ifHCInOctets\", 1s) *8 AS \"Inbound\", derivative(\"ifHCOutOctets\", 1s) *-8 AS \"Outbound\" FROM \"snmp\" WHERE (\"device\" = 'switch' AND \"ifName\" = 'Te1/0/1') AND $timeFilter GROUP BY \"ifName\"",
     "select": [
      [
       { "params": [ "ifHCInOctets" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "*8" ], "type": "math" },
       { "params": [ "Inbound" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=", "value": "switch" },
      { "condition": "AND", "key": "ifName", "operator": "=", "value": "Te1/0/1" }
     ]
    },
    {
     "alias": "3850 Gi$tag_ifName",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "ifName" ], "type": "tag" }
     ],
     "measurement": "snmp",
     "query": "SELECT non_negative_derivative(mean(\"ifHCInOctets\"), 1s) *8 AS \"Outbound\", non_negative_derivative(mean(\"ifHCOutOctets\"), 1s) *-8 AS \"Outbound\" FROM \"snmp\" WHERE (\"device\" = 'switch' AND \"ifName\" = 'Te1/1/3') AND $timeFilter GROUP BY time($interval), \"ifName\"",
     "select": [
      [
       { "params": [ "ifHCInOctets" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "*8" ], "type": "math" },
       { "params": [ "Inbound" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=", "value": "switch" },
      { "condition": "AND", "key": "ifName", "operator": "=", "value": "Te1/1/3" }
     ]
    },
    {
     "alias": "3850 Gi$tag_ifName",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "ifName" ], "type": "tag" }
     ],
     "measurement": "snmp",
     "query": "SELECT non_negative_derivative(mean(\"ifHCInOctets\"), 1s) *8 AS \"Outbound\", non_negative_derivative(mean(\"ifHCOutOctets\"), 1s) *-8 AS \"Outbound\" FROM \"snmp\" WHERE (\"device\" = 'switch' AND \"ifName\" = 'Te1/1/3') AND $timeFilter GROUP BY time($interval), \"ifName\"",
     "select": [
      [
       { "params": [ "ifHCInOctets" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "*8" ], "type": "math" },
       { "params": [ "Inbound" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=", "value": "switch" },
      { "condition": "AND", "key": "ifName", "operator": "=", "value": "Te1/0/23" }
     ]
    },
    {
     "alias": "3850 Gi$tag_ifName",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "ifName" ], "type": "tag" }
     ],
     "measurement": "snmp",
     "query": "SELECT non_negative_derivative(mean(\"ifHCInOctets\"), 1s) *8 AS \"Outbound\", non_negative_derivative(mean(\"ifHCOutOctets\"), 1s) *-8 AS \"Outbound\" FROM \"snmp\" WHERE (\"device\" = 'switch' AND \"ifName\" = 'Te1/1/3') AND $timeFilter GROUP BY time($interval), \"ifName\"",
     "select": [
      [
       { "params": [ "ifHCInOctets" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "*8" ], "type": "math" },
       { "params": [ "Inbound" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=", "value": "switch" },
      { "condition": "AND", "key": "ifName", "operator": "=", "value": "Te1/0/24" }
     ]
    }
   ]
  },
  {
   "title": "Network Monitoring - Output",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "DLink Gi$tag_ifName",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "ifName" ], "type": "tag" }
     ],
     "measurement": "snmp",
     "query": "SELECT derivative(\"ifHCInOctets\", 1s) *8 AS \"Inbound\", derivative(\"ifHCOutOctets\", 1s) *-8 AS \"Outbound\" FROM \"snmp\" WHERE (\"device\" = 'switch' AND \"ifName\" = '1/48') AND $timeFilter GROUP BY \"ifName\"",
     "select": [
      [
       { "params": [ "ifHCOutOctets" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "*8" ], "type": "math" },
       { "params": [ "Outbound" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=", "value": "switch" },
      { "condition": "AND", "key": "ifName", "operator": "=", "value": "1/48" }
     ]
    },
    {
     "alias": "3850 Gi$tag_ifName",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "ifName" ], "type": "tag" }
     ],
     "measurement": "snmp",
     "query": "SELECT derivative(\"ifHCInOctets\", 1s) *8 AS \"Inbound\", derivative(\"ifHCOutOctets\", 1s) *-8 AS \"Outbound\" FROM \"snmp\" WHERE (\"device\" = 'switch' AND \"ifName\" = 'Te1/0/1') AND $timeFilter GROUP BY \"ifName\"",
     "select": [
      [
       { "params": [ "ifHCOutOctets" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "*8" ], "type": "math" },
       { "params": [ "Outbound" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=", "value": "switch" },
      { "condition": "AND", "key": "ifName", "operator": "=", "value": "Te1/0/1" }
     ]
    },
    {
     "alias": "3850 Gi$tag_ifName",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "ifName" ], "type": "tag" }
     ],
     "measurement": "snmp",
     "query": "SELECT non_negative_derivative(first(\"ifHCOutOctets\"), 1s) *8 AS \"Outbound\" FROM \"snmp\" WHERE (\"device\" = 'switch' AND \"ifName\" = 'Te1/1/3') AND $timeFilter GROUP BY time($interval), \"ifName\"",
     "select": [
      [
       { "params": [ "ifHCOutOctets" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "*8" ], "type": "math" },
       { "params": [ "Outbound" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=", "value": "switch" },
      { "condition": "AND", "key": "ifName", "operator": "=", "value": "Te1/1/3" }
     ]
    },
    {
     "alias": "3850 Gi$tag_ifName",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "ifName" ], "type": "tag" }
     ],
     "measurement": "snmp",
     "query": "SELECT non_negative_derivative(first(\"ifHCOutOctets\"), 1s) *8 AS \"Outbound\" FROM \"snmp\" WHERE (\"device\" = 'switch' AND \"ifName\" = 'Te1/1/3') AND $timeFilter GROUP BY time($interval), \"ifName\"",
     "select": [
      [
       { "params": [ "ifHCOutOctets" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "*8" ], "type": "math" },
       { "params": [ "Outbound" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=", "value": "switch" },
      { "condition": "AND", "key": "ifName", "operator": "=", "value": "Te1/0/23" }
     ]
    },
    {
     "alias": "3850 Gi$tag_ifName",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "ifName" ], "type": "tag" }
     ],
     "measurement": "snmp",
     "query": "SELECT non_negative_derivative(first(\"ifHCOutOctets\"), 1s) *8 AS \"Outbound\" FROM \"snmp\" WHERE (\"device\" = 'switch' AND \"ifName\" = 'Te1/1/3') AND $timeFilter GROUP BY time($interval), \"ifName\"",
     "select": [
      [
       { "params": [ "ifHCOutOctets" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "*8" ], "type": "math" },
       { "params": [ "Outbound" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=", "value": "switch" },
      { "condition": "AND", "key": "ifName", "operator": "=", "value": "Te1/0/24" }
     ]
    }
   ]
  },
  {
   "title": "Earthcam Monitoring",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "device" ], "type": "tag" }
     ],
     "measurement": "ping",
     "select": [
      [
       { "params": [ "average_response_ms" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "webcam" },
      { "condition": "AND", "key": "device", "operator": "=", "value": "dome" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "device" ], "type": "tag" }
     ],
     "measurement": "ping",
     "select": [
      [
       { "params": [ "average_response_ms" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "webcam" },
      { "condition": "AND", "key": "device", "operator": "=", "value": "basefacility" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "device" ], "type": "tag" }
     ],
     "measurement": "ping",
     "select": [
      [
       { "params": [ "average_response_ms" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "webcam" },
      { "condition": "AND", "key": "device", "operator": "=", "value": "hill" }
     ]
    }
   ]
  },
  {
   "title": "Ping to ACI",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "ping",
     "select": [
      [
       { "params": [ "average_response_ms" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "enclave", "operator": "=", "value": "net" },
      { "condition": "AND", "key": "node_name", "operator": "=", "value": "aci_core" }
     ]
    }
   ]
  },
  {
   "title": "Network Monitoring - Input",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "DistSwitch Gi$tag_ifName",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "ifName" ], "type": "tag" }
     ],
     "measurement": "snmp",
     "query": "SELECT derivative(\"ifHCInOctets\", 1s) *8 AS \"Inbound\", derivative(\"ifHCOutOctets\", 1s) *-8 AS \"Outbound\" FROM \"snmp\" WHERE (\"device\" = 'switch' AND \"ifName\" = '1/48') AND $timeFilter GROUP BY \"ifName\"",
     "select": [
      [
       { "params": [ "ifHCInOctets" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "*8" ], "type": "math" },
       { "params": [ "Inbound" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=", "value": "switch" },
      { "condition": "AND", "key": "ifName", "operator": "=", "value": "Te1/0/23" }
     ]
    },
    {
     "alias": "DistSwitch Gi$tag_ifName",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "ifName" ], "type": "tag" }
     ],
     "measurement": "snmp",
     "query": "SELECT derivative(\"ifHCInOctets\", 1s) *8 AS \"Inbound\", derivative(\"ifHCOutOctets\", 1s) *-8 AS \"Outbound\" FROM \"snmp\" WHERE (\"device\" = 'switch' AND \"ifName\" = 'Te1/0/1') AND $timeFilter GROUP BY \"ifName\"",
     "select": [
      [
       { "params": [ "ifHCOutOctets" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "*8" ], "type": "math" },
       { "params": [ "Inbound" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=", "value": "switch" },
      { "condition": "AND", "key": "ifName", "operator": "=", "value": "Te1/0/23" }
     ]
    }
   ]
  }
 ]
}