{
 "title": "Services Monitoring",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "comparison_time", "label": "Services found T ago", "query": "1h,6h,12h,1d,7d,14d,30d" }
  ]
 },
 "panels": [
  { "title": "Cerro Pachon", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "datacenter" },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" }
     ],
     "measurement": "cpu",
     "select": [
      [
       { "params": [ "usage_user" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "datacenter", "operator": "=", "value": "cp" }
     ]
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" }
     ],
     "measurement": "mem",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "datacenter", "operator": "=", "value": "cp" }
     ]
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" }
     ],
     "measurement": "disk",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "datacenter", "operator": "=", "value": "cp" }
     ]
    }
   ]
  },
  {
   "title": "Process State Generic",
   "type": "yesoreyeram-boomtable-panel",
   "description": "Green = up\nRed = down",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "alias": "$tag_host.count24",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "procstat",
     "query": "SELECT count(\"first\") FROM (SELECT first(pid) FROM procstat WHERE time > now()-$comparison_time AND datacenter = 'cp'  GROUP BY systemd_unit) group by host ",
     "select": [
      [
       { "params": [ "pid" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    },
    {
     "alias": "$tag_host.count",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "procstat",
     "query": "SELECT count(\"first\") FROM (SELECT first(pid) FROM procstat WHERE time > now()-2m AND datacenter = 'cp'  GROUP BY systemd_unit)  group by host",
     "select": [
      [
       { "params": [ "pid" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    },
    {
     "alias": "$tag_host.$tag_systemd_unit",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "systemd_unit" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "procstat",
     "query": "SELECT last(\"pid\") FROM \"autogen\".\"procstat\" WHERE (\"datacenter\" = 'cp') AND $timeFilter  GROUP BY time(1m), \"host\", \"systemd_unit\" fill(0)",
     "select": [
      [
       { "params": [ "pid" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "datacenter", "operator": "=", "value": "cp" }
     ]
    }
   ]
  },
  { "title": "La Serena", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" }
     ],
     "measurement": "cpu",
     "select": [
      [
       { "params": [ "usage_user" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "datacenter", "operator": "=", "value": "ls" }
     ]
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" }
     ],
     "measurement": "mem",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "datacenter", "operator": "=", "value": "ls" }
     ]
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" }
     ],
     "measurement": "disk",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "datacenter", "operator": "=", "value": "ls" }
     ]
    }
   ]
  },
  {
   "title": "Process State Generic",
   "type": "yesoreyeram-boomtable-panel",
   "description": "Green = up\nRed = down",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 31 },
   "targets": [
    {
     "alias": "$tag_host.count24",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "procstat",
     "query": "SELECT count(\"first\") FROM (SELECT first(pid) FROM procstat WHERE time > now()-$comparison_time AND datacenter = 'ls'  GROUP BY systemd_unit) group by host ",
     "select": [
      [
       { "params": [ "pid" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    },
    {
     "alias": "$tag_host.count",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "procstat",
     "query": "SELECT count(\"first\") FROM (SELECT first(pid) FROM procstat WHERE time > now()-2m AND datacenter = 'ls'  GROUP BY systemd_unit)  group by host",
     "select": [
      [
       { "params": [ "pid" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    },
    {
     "alias": "$tag_host.$tag_systemd_unit",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "systemd_unit" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "procstat",
     "query": "SELECT last(\"pid\") FROM \"autogen\".\"procstat\" WHERE (\"datacenter\" = 'cp') AND $timeFilter  GROUP BY time(1m), \"host\", \"systemd_unit\" fill(0)",
     "select": [
      [
       { "params": [ "pid" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "datacenter", "operator": "=", "value": "ls" }
     ]
    }
   ]
  }
 ]
}