{
 "title": "Summit Electrical Monitoring",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Current consumption all phases",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "amp" }
   ],
   "targets": [
    {
     "alias": "Output current phase 1",
     "measurement": "xupsOutputTable",
     "select": [
      [
       { "params": [ "xupsOutputCurrent" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "xupsOutputPhase", "operator": "=", "value": "1" }
     ]
    },
    {
     "alias": "Output current phase 2",
     "measurement": "xupsOutputTable",
     "select": [
      [
       { "params": [ "xupsOutputCurrent" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "xupsOutputPhase", "operator": "=", "value": "2" }
     ]
    },
    {
     "alias": "Output current phase 3",
     "measurement": "xupsOutputTable",
     "select": [
      [
       { "params": [ "xupsOutputCurrent" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "xupsOutputPhase", "operator": "=", "value": "3" }
     ]
    }
   ]
  },
  {
   "title": "Power Consumption",
   "type": "singlestat",
   "description": "Power consumption 3 phase combined",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "format": "watth",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "xupsOutputTable",
     "query": "SELECT mean(\"sum_xupsOutputWatts\") FROM  (SELECT sum(\"xupsOutputWatts\") as \"sum_xupsOutputWatts\"  FROM \"xupsOutputTable\" WHERE (\"xupsOutputPhase\" = '1' OR \"xupsOutputPhase\" = '2' OR \"xupsOutputPhase\" = '3') AND $timeFilter GROUP BY time($interval))",
     "select": [
      [
       { "params": [ "xupsOutputWatts" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "xupsOutputPhase", "operator": "=", "value": "1" },
      { "condition": "OR", "key": "xupsOutputPhase", "operator": "=", "value": "2" },
      { "condition": "OR", "key": "xupsOutputPhase", "operator": "=", "value": "3" }
     ]
    }
   ]
  },
  {
   "title": "Input Power Consumption ALL phases",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "alias": "Input Phase 1",
     "measurement": "xupsInputTable",
     "select": [
      [
       { "params": [ "xupsInputWatts" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "xupsInputPhase", "operator": "=", "value": "1" }
     ]
    },
    {
     "alias": "Input Phase 2",
     "measurement": "xupsInputTable",
     "select": [
      [
       { "params": [ "xupsInputWatts" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "xupsInputPhase", "operator": "=", "value": "2" }
     ]
    },
    {
     "alias": "Input Phase 3",
     "measurement": "xupsInputTable",
     "select": [
      [
       { "params": [ "xupsInputWatts" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "xupsInputPhase", "operator": "=", "value": "3" }
     ]
    }
   ]
  },
  {
   "title": "Output Power Consumption ALL phases",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "alias": "Output Phase 1",
     "measurement": "xupsOutputTable",
     "select": [
      [
       { "params": [ "xupsOutputWatts" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "xupsOutputPhase", "operator": "=", "value": "1" }
     ]
    },
    {
     "alias": "Output Phase 2",
     "measurement": "xupsOutputTable",
     "select": [
      [
       { "params": [ "xupsOutputWatts" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "xupsOutputPhase", "operator": "=", "value": "2" }
     ]
    },
    {
     "alias": "Output Phase 3",
     "measurement": "xupsOutputTable",
     "select": [
      [
       { "params": [ "xupsOutputWatts" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "xupsOutputPhase", "operator": "=", "value": "3" }
     ]
    }
   ]
  },
  {
   "title": "Battery time remaining",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "alias": "Battery time remaining",
     "measurement": "ups1",
     "select": [
      [
       { "params": [ "xupsBatTimeRemaining" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Ambient Temperature",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "alias": "Ambient Temperature",
     "measurement": "ups1",
     "select": [
      [
       { "params": [ "xupsEnvAmbientTemp" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Battery Current",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 18 },
   "yaxes": [
    { "format": "amp" }
   ],
   "targets": [
    {
     "alias": "Battery Current",
     "measurement": "ups1",
     "select": [
      [
       { "params": [ "xupsBatCurrent" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Input Voltage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Input Phase $tag_xupsInputPhase",
     "groupBy": [
      { "params": [ "xupsInputPhase" ], "type": "tag" }
     ],
     "measurement": "xupsInputTable",
     "select": [
      [
       { "params": [ "xupsInputVoltage" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Output Voltage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Output phase $tag_xupsOutputPhase",
     "groupBy": [
      { "params": [ "xupsOutputPhase" ], "type": "tag" }
     ],
     "measurement": "xupsOutputTable",
     "select": [
      [
       { "params": [ "xupsOutputVoltage" ], "type": "field" }
      ]
     ]
    }
   ]
  }
 ]
}